run:
	echo "starting cmd by default"
	go run parseAndRun.go -arg="run cmd"

run-cmd:
	echo "starting cmd"
	go run parseAndRun.go -arg="run cmd"

run-powershell:
	make run-ps

run-ps:
	echo "starting powershell"
	go run parseAndRun.go -arg="run powershell"

run-chrome:
	go run parseAndRun.go -arg="run chrome"